### PR TITLE
issue-614 resolve version from model properties if necessary

### PR DESCRIPTION
**Pull request by TorstenKruse**
fixes issue 614 for reports

### CODE REVIEW

**Review by ajarmoniuk — CHANGES_REQUESTED** [review]
Please don't forget about adding tests testing your changes :)

You can e.g. create a simple it test (or more) or add one or more methods to DependencyUpdatesReportMojoTest.

**Comment by TorstenKruse** [comment]
Still unsure if this is the right way to implement the test, please review. Thanks.

BTW: IntelliJ is complaining about org.codehaus.mojo.versions.model.RuleSet - where to find this class?

**Comment by TorstenKruse** [comment]
I'm sorry, renaming the branch seems to auto close the PR, please go on here: https://github.com/mojohaus/versions-maven-plugin/pull/797

**Comment by ajarmoniuk** [comment]
It's generated from a Modello model. Please run `mvn generate-sources` and then reload the maven project in IntelliJ.

________________________________

**Pull request closed without merging**
