### PR TITLE
Resolves #888: New optional parameter to SetMojo: interpolateProperties

### LINKED ISSUE #888: Regression in 2.14.2: version not updated
I am currently investigating what i believe to be a regression in versions-maven-plugin 2.14.2.

Basically versions:set no longer seems to work as designed:
```
+ mvn versions:set -DnewVersion=2.0.6-UpdateVersionsPlugin-SNAPSHOT -DoldVersion=*
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.somewhere.di:di-business-model >-----------------
[INFO] Building di-business-model 2.0.6-UpdateVersionsPlugin-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.14.2:set (default-cli) @ di-business-model ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/iness-model_UpdateVersionsPlugin
[INFO] Processing change of com.somewhere.di:di-business-model:* -> 2.0.6-UpdateVersionsPlugin-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.905 s
[INFO] Finished at: 2022-12-30T12:01:03+01:00
[INFO] -----------------------------------------------------------------------
```
the version is unaffected after this

This works in 2.14.1:
```
+ mvn versions:set -DnewVersion=2.0.6-UpdateVersionsPlugin-SNAPSHOT -DoldVersion=*
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.somewhere.di:di-business-model >-----------------
[INFO] Building di-business-model 2.0.6-UpdateVersionsPlugin-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.14.1:set (default-cli) @ di-business-model ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /home/jenkins/workspace/iness-model_UpdateVersionsPlugin
[INFO] Processing change of com.somewhere.di:di-business-model:* -> 2.0.6-UpdateVersionsPlugin-SNAPSHOT
[INFO] Processing com.somewhere.di:di-business-model
[INFO]     Updating project com.somewhere.di:di-business-model
[INFO]         from version  to 2.0.6-UpdateVersionsPlugin-SNAPSHOT
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.734 s
[INFO] Finished at: 2022-12-30T11:50:35+01:00
[INFO] ------------------------------------------------------------------------
```

Unfortunately this only fails when run in our Jenkins.
I am still investigating this. Any suggestions appreciated.

### PR DESCRIPTION
**Pull request by ajarmoniuk**
- allows to disable property interpolation, so that it's possible to match against raw property values as well as replace properties with interpolated values if the value is the same as the property value

This is my take on resolving the problem which occurs when the user wants to match against a version which is the same as the interpolated property value. If this is the case, by default, the file is left unchanged, so that it continues to contain the properties.

If the new parameter is employed, it is possible to disable interpolation for such cases, but one needs to match against the raw value (e.g. use the property name, or `*`), and the value will be replaced.

### CODE REVIEW

**Comment by ajarmoniuk** [comment]
@slawekjaranowski lots of new PR, here's one more :)

**Comment by ajarmoniuk** [comment]
@slawekjaranowski why did you close this PR?

**Comment by pzygielo** [comment]
> why did you close this PR?

Commit with closing keyword was pushed to master.

**Comment by ajarmoniuk** [comment]
Please reopen.

**Comment by ajarmoniuk** [comment]
The commit message was ok: there is both an issue 889 as well as a PR 889....

**Comment by pzygielo** [comment]
> there is both an issue 889 as well as a PR 889....

Is that possible?

**Comment by ajarmoniuk** [comment]
@pzygielo no:

[PR #889](https://github.com/mojohaus/versions/pull/889)

[Issue #891](https://github.com/mojohaus/versions/pull/889)

**Comment by ajarmoniuk** [comment]
So indeed wrong commit message.

**Comment by slawekjaranowski** [comment]
> @slawekjaranowski why did you close this PR?

Was classed because was mentioned in merged PR

> closed this in https://github.com/mojohaus/versions/commit/edf4e2f76064e74669ab0263025c729880bf7118

**Comment by ajarmoniuk** [comment]
Should I create a new one?

**Comment by slawekjaranowski** [comment]
Reopened 😄

**Pull request merged**
